apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: dind-storage-INSTALLATION_NAME
  namespace: RUNNERS_NAMESPACE
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: STORAGE_SIZE
  storageClassName: standard