name: Test Rootless Containers
on:
  workflow_dispatch:
  push:
    paths:
      - 'test-rootless-containers.yaml'

jobs:
  test-rootless:
    runs-on: arc-runner-rkoster-rubionic-workspace
    steps:
      - name: Check Environment Variables
        run: |
          echo "=== Environment Variables ==="
          echo "ROOTLESS_CONTAINERS: $ROOTLESS_CONTAINERS"
          echo "CONTAINER_RUNTIME: $CONTAINER_RUNTIME"
          
      - name: Check Container Runtime Installation
        run: |
          echo "=== Checking Container Runtimes ==="
          which podman || echo "podman not found in PATH"
          which buildah || echo "buildah not found in PATH"
          which docker || echo "docker not found in PATH"
          
      - name: Check Rootless Container Configuration
        run: |
          echo "=== Checking Rootless Configuration ==="
          echo "Home directory contents:"
          ls -la /home/runner/ || true
          echo "Work directory contents:"
          ls -la /home/runner/_work/ || true
          echo "Config directory:"
          ls -la /home/runner/_work/.config/ || true
          echo "Containers config:"
          cat /home/runner/_work/.config/containers/containers.conf || echo "containers.conf not found"
          
      - name: Test Container Operations
        run: |
          echo "=== Testing Container Operations ==="
          if command -v podman &> /dev/null; then
            echo "Testing podman..."
            podman --version
            podman info || true
            echo "Attempting to run hello world container..."
            podman run --rm hello-world || echo "podman run failed"
          else
            echo "podman not available"
          fi
          
          if command -v buildah &> /dev/null; then
            echo "Testing buildah..."
            buildah --version
            buildah info || true
          else
            echo "buildah not available"
          fi